apiVersion: batch/v1
kind: Job
metadata:
  name: oneshot-parallel-job
spec:
  completions: 10
  parallelism: 2
  template:
    spec:
      containers:
      - name: worker
        image: busybox
        command: ["sh", "-c", "echo Hello from job && sleep 5"]
      restartPolicy: Never
